#!/bin/bash

# ami id from https://wiki.centos.org/Cloud/AWS
# aws ec2 run-instances --image-id ami-0c2aba6c --count 1 --instance-type t1.micro --key-name oregon-region-keypair --security-group-ids sg-90f631ea --subnet-id subnet-xxxxxxxx

aws ec2 run-instances --image-id ami-0c2aba6c --count 1 --instance-type t2.micro --key-name oregon-region-keypair --security-group-ids sg-90f631ea
