---
- name: Copy files
  hosts: all
  roles:
    - remote_setup

- name: Setup base system
  hosts: all
  roles:
    - base

- name: setup development environment
  hosts: devboxes
  roles:
    - developer
